name: expense_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Adds currency formatting
  intl: ^0.18.1
  # Adds modern font styles
  google_fonts: ^6.1.0
  # Database for persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # For finding where to save the file
  path_provider: ^2.1.1
  # For sharing the file (Export)
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true